using Microsoft.EntityFrameworkCore.Migrations;

namespace web_api.Migrations
{
    public partial class AutoGeneratedId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "SpotifyUri",
                table: "Albums",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SpotifyUri",
                table: "Albums");
        }
    }
}
