#!/bin/sh
echo "Pandoc converting .docx to .md ..."

cd ./anteprojeto
pandoc ./main.docx -s --extract-media=./pandoc -o ./main.md -w gfm
git add ./main.md

cd ../tcc-i
pandoc ./main.docx -s --extract-media=./pandoc -o ./main.md -w gfm
git add ./main.md

echo "Pandoc converting done."